# Generated by Django 4.2.4 on 2023-08-18 15:55

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('personal_invite_code', models.IntegerField(default=users.models.UserProfle.generate_random_number)),
                ('stranger_invite_code', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
